Update workflows
Signed-off-by: Akshay peherkar <95123298+Akshayp02@users.noreply.github.com>

diff --git a/.github/workflows/Build_Test.yml b/.github/workflows/Build_Test.yml
--- a/.github/workflows/Build_Test.yml
+++ b/.github/workflows/Build_Test.yml
@@ -1,33 +1,36 @@
-name: Build and Test 
-
+name: Build and Test
 
 on:
-
   push:
-    branches: [ master ]
+    branches:
+      - master
   pull_request:
-    branches: [ master ]
-
+    branches:
+      - master
 
 jobs:
   build_test:
-   
     runs-on: ubuntu-latest
 
     strategy:
       matrix:
-        node-version: [14.x, 15.x, 16.x]
+        node-version: ['14', '15', '16']
 
-   
     steps:
-      
-      - uses: actions/checkout@v2
-      - name: Use Node.js ${{ matrix.node-version }}
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Setup Node.js
         uses: actions/setup-node@v2
         with:
           node-version: ${{ matrix.node-version }}
-      - name: npm ci, build and test
+
+      - name: Install dependencies and build
         run: |
           npm ci
           npm run build --if-present
-          npm test   
+          npm test
+          if [ $? -ne 0 ]; then
+            echo "npm test failed"
+            exit 1
+          fi
